# caller workflow
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: pdevops87/roboshop-frontend-v1/.github/workflows/ci.yml@main
    with:
      appName: "frontend"
      toolName: "nginx"

