# This is a basic workflow to help you get started with Actions

name: frontend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t frontend .
        name: build a frontend docker image

  dev:
    needs: docker
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
        repository: pdevops87/roboshop-helm-v1
      - name: connect to kubernetes api through kubeconfig
        run: echo aws eks update-kubeconfig --name dev
      - name: deploy app
        run: echo helm upgrade -i frontend -f pass-values-templates/frontend.yaml






          
