on:
  push:
    branches: [ "main" ]

jobs:
  call-workflow-passing-data:
    uses: pedvops87/https://github.com/pdevops87/roboshop-frontend-v1/.github/workflows/ci.yml@main
    with:
      appName: frontend

