# This is a basic workflow to help you get started with Actions

name: frontend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building frontend"
        name: frontend



          
